"""
Export trained policy to C header for firmware deployment.
Matches rl_tools format for compatibility with existing firmware.
"""

import torch
import numpy as np
from typing import Optional, Dict
from pathlib import Path


def export_to_c_header(
    policy,
    obs_mean: torch.Tensor,
    obs_std: torch.Tensor,
    output_path: str,
    namespace: str = "rl_tools::rl::environments::l2f"
) -> str:
    """
    Export policy weights and normalization params to C header.
    
    Args:
        policy: Trained ActorCritic policy
        obs_mean: Observation mean for normalization (13,)
        obs_std: Observation std for normalization (13,)
        output_path: Path for output .h file
        namespace: C++ namespace
        
    Returns:
        Path to generated header file
    """
    # Get underlying model if compiled
    model = policy
    if hasattr(model, '_orig_mod'):
        model = model._orig_mod
    
    # Extract weights from actor network
    weights = model.export_weights()
    
    # Get weights - handle both key naming conventions
    if 'actor_l1_w' in weights:
        # New naming convention (already numpy)
        fc1_w = weights['actor_l1_w']
        fc1_b = weights['actor_l1_b']
        fc2_w = weights['actor_l2_w']
        fc2_b = weights['actor_l2_b']
        fc3_w = weights['actor_l3_w']
        fc3_b = weights['actor_l3_b']
        log_std = weights['log_std']
    else:
        # Legacy naming convention (torch tensors)
        fc1_w = weights['actor.fc1.weight'].cpu().numpy()
        fc1_b = weights['actor.fc1.bias'].cpu().numpy()
        fc2_w = weights['actor.fc2.weight'].cpu().numpy()
        fc2_b = weights['actor.fc2.bias'].cpu().numpy()
        fc3_w = weights['actor.fc3.weight'].cpu().numpy()
        fc3_b = weights['actor.fc3.bias'].cpu().numpy()
        log_std = weights['actor.log_std'].cpu().numpy()
    
    obs_mean_np = obs_mean.cpu().numpy()
    obs_std_np = obs_std.cpu().numpy()
    
    # Generate header content
    header = generate_header(
        fc1_w, fc1_b,
        fc2_w, fc2_b,
        fc3_w, fc3_b,
        log_std,
        obs_mean_np, obs_std_np,
        namespace
    )
    
    # Write file
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header)
    
    print(f"Exported policy to: {output_path}")
    return output_path


def generate_header(
    fc1_w, fc1_b,
    fc2_w, fc2_b,
    fc3_w, fc3_b,
    log_std,
    obs_mean, obs_std,
    namespace: str
) -> str:
    """Generate C header content"""
    
    obs_dim = fc1_w.shape[1]
    hidden_dim = fc1_w.shape[0]
    action_dim = fc3_w.shape[0]
    
    lines = []
    
    # Header guard and includes
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Auto-generated by PPO training")
    lines.append("// Do not edit manually")
    lines.append("")
    lines.append("#include <cmath>")
    lines.append("")
    
    # Namespace
    lines.append(f"namespace {namespace} {{")
    lines.append("")
    
    # Network dimensions
    lines.append(f"    constexpr int OBS_DIM = {obs_dim};")
    lines.append(f"    constexpr int HIDDEN_DIM = {hidden_dim};")
    lines.append(f"    constexpr int ACTION_DIM = {action_dim};")
    lines.append("")
    
    # Observation normalization
    lines.append("    // Observation normalization parameters")
    lines.append(f"    constexpr float OBS_MEAN[{obs_dim}] = {{")
    lines.append("        " + ", ".join(f"{x:.8f}f" for x in obs_mean))
    lines.append("    };")
    lines.append("")
    lines.append(f"    constexpr float OBS_STD[{obs_dim}] = {{")
    lines.append("        " + ", ".join(f"{x:.8f}f" for x in obs_std))
    lines.append("    };")
    lines.append("")
    
    # Layer 1 weights (row-major)
    lines.append(f"    // Layer 1: {obs_dim} -> {hidden_dim}")
    lines.append(f"    constexpr float FC1_W[{hidden_dim}][{obs_dim}] = {{")
    for row in fc1_w:
        lines.append("        {" + ", ".join(f"{x:.8f}f" for x in row) + "},")
    lines.append("    };")
    lines.append("")
    
    lines.append(f"    constexpr float FC1_B[{hidden_dim}] = {{")
    lines.append("        " + ", ".join(f"{x:.8f}f" for x in fc1_b))
    lines.append("    };")
    lines.append("")
    
    # Layer 2 weights
    lines.append(f"    // Layer 2: {hidden_dim} -> {hidden_dim}")
    lines.append(f"    constexpr float FC2_W[{hidden_dim}][{hidden_dim}] = {{")
    for row in fc2_w:
        lines.append("        {" + ", ".join(f"{x:.8f}f" for x in row) + "},")
    lines.append("    };")
    lines.append("")
    
    lines.append(f"    constexpr float FC2_B[{hidden_dim}] = {{")
    lines.append("        " + ", ".join(f"{x:.8f}f" for x in fc2_b))
    lines.append("    };")
    lines.append("")
    
    # Layer 3 weights (output)
    lines.append(f"    // Layer 3: {hidden_dim} -> {action_dim}")
    lines.append(f"    constexpr float FC3_W[{action_dim}][{hidden_dim}] = {{")
    for row in fc3_w:
        lines.append("        {" + ", ".join(f"{x:.8f}f" for x in row) + "},")
    lines.append("    };")
    lines.append("")
    
    lines.append(f"    constexpr float FC3_B[{action_dim}] = {{")
    lines.append("        " + ", ".join(f"{x:.8f}f" for x in fc3_b))
    lines.append("    };")
    lines.append("")
    
    # Inference function
    lines.append("    // Inference function - deterministic action")
    lines.append("    inline void forward(const float* obs_raw, float* action_out) {")
    lines.append("        float obs[OBS_DIM];")
    lines.append("        float h1[HIDDEN_DIM];")
    lines.append("        float h2[HIDDEN_DIM];")
    lines.append("")
    lines.append("        // Normalize observation")
    lines.append("        for (int i = 0; i < OBS_DIM; i++) {")
    lines.append("            obs[i] = (obs_raw[i] - OBS_MEAN[i]) / OBS_STD[i];")
    lines.append("        }")
    lines.append("")
    lines.append("        // Layer 1: input -> hidden (tanh)")
    lines.append("        for (int i = 0; i < HIDDEN_DIM; i++) {")
    lines.append("            h1[i] = FC1_B[i];")
    lines.append("            for (int j = 0; j < OBS_DIM; j++) {")
    lines.append("                h1[i] += FC1_W[i][j] * obs[j];")
    lines.append("            }")
    lines.append("            h1[i] = tanhf(h1[i]);")
    lines.append("        }")
    lines.append("")
    lines.append("        // Layer 2: hidden -> hidden (tanh)")
    lines.append("        for (int i = 0; i < HIDDEN_DIM; i++) {")
    lines.append("            h2[i] = FC2_B[i];")
    lines.append("            for (int j = 0; j < HIDDEN_DIM; j++) {")
    lines.append("                h2[i] += FC2_W[i][j] * h1[j];")
    lines.append("            }")
    lines.append("            h2[i] = tanhf(h2[i]);")
    lines.append("        }")
    lines.append("")
    lines.append("        // Layer 3: hidden -> action (tanh output)")
    lines.append("        for (int i = 0; i < ACTION_DIM; i++) {")
    lines.append("            action_out[i] = FC3_B[i];")
    lines.append("            for (int j = 0; j < HIDDEN_DIM; j++) {")
    lines.append("                action_out[i] += FC3_W[i][j] * h2[j];")
    lines.append("            }")
    lines.append("            action_out[i] = tanhf(action_out[i]);")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    
    # Action scaling for Crazyflie
    lines.append("    // Convert normalized action to thrust commands")
    lines.append("    // Actions are in [-1, 1], scale to [0, max_thrust]")
    lines.append("    constexpr float MAX_THRUST = 0.06f;  // N per motor")
    lines.append("    constexpr float HOVER_THRUST = 0.0663f;  // mg/4 per motor")
    lines.append("")
    lines.append("    inline void action_to_thrust(const float* action, float* thrust) {")
    lines.append("        for (int i = 0; i < ACTION_DIM; i++) {")
    lines.append("            // Map [-1, 1] to [0, MAX_THRUST]")
    lines.append("            thrust[i] = (action[i] + 1.0f) * 0.5f * MAX_THRUST;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    
    # Safe inference with thrust ramping
    lines.append("    // Safe inference with thrust ramping for takeoff")
    lines.append("    inline void forward_safe(")
    lines.append("        const float* obs_raw,")
    lines.append("        float* thrust,")
    lines.append("        float ramp_factor  // 0 to 1, increases over first 1-2 seconds")
    lines.append("    ) {")
    lines.append("        float action[ACTION_DIM];")
    lines.append("        forward(obs_raw, action);")
    lines.append("        action_to_thrust(action, thrust);")
    lines.append("")
    lines.append("        // Apply ramp for smooth takeoff")
    lines.append("        for (int i = 0; i < ACTION_DIM; i++) {")
    lines.append("            thrust[i] *= ramp_factor;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    
    # Close namespace
    lines.append(f"}}  // namespace {namespace}")
    lines.append("")
    
    return "\n".join(lines)


def export_onnx(
    policy,
    obs_mean: torch.Tensor,
    obs_std: torch.Tensor,
    output_path: str
) -> str:
    """
    Export policy to ONNX format.
    
    Args:
        policy: Trained ActorCritic policy
        obs_mean: Observation mean
        obs_std: Observation std  
        output_path: Path for output .onnx file
        
    Returns:
        Path to generated ONNX file
    """
    # Get underlying model if compiled
    model = policy
    if hasattr(model, '_orig_mod'):
        model = model._orig_mod
    
    model.eval()
    
    # Create wrapper that includes normalization
    class PolicyWithNorm(torch.nn.Module):
        def __init__(self, actor, obs_mean, obs_std):
            super().__init__()
            self.actor = actor
            self.register_buffer('obs_mean', obs_mean)
            self.register_buffer('obs_std', obs_std)
        
        def forward(self, x):
            # Normalize
            x = (x - self.obs_mean) / self.obs_std
            # Forward through actor (Sequential with layers at [0], [2], [4])
            return self.actor(x)
    
    wrapper = PolicyWithNorm(model.actor, obs_mean, obs_std)
    wrapper.eval()
    
    # Create dummy input
    dummy_input = torch.zeros(1, obs_mean.shape[0], device=obs_mean.device)
    
    # Export
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    torch.onnx.export(
        wrapper,
        dummy_input,
        output_path,
        input_names=['observation'],
        output_names=['action'],
        dynamic_axes={
            'observation': {0: 'batch_size'},
            'action': {0: 'batch_size'}
        },
        opset_version=11
    )
    
    print(f"Exported ONNX model to: {output_path}")
    return output_path


def validate_export(
    policy,
    obs_mean: torch.Tensor,
    obs_std: torch.Tensor,
    header_path: str,
    num_samples: int = 1000,
    tolerance: float = 1e-5
) -> bool:
    """
    Validate C header export matches PyTorch output.
    
    This compiles and runs the C code to verify correctness.
    """
    import subprocess
    import tempfile
    import os
    
    # Get underlying model if compiled
    model = policy
    if hasattr(model, '_orig_mod'):
        model = model._orig_mod
    
    model.eval()
    
    # Generate test observations
    test_obs = torch.randn(num_samples, obs_mean.shape[0], device=obs_mean.device)
    
    # Get PyTorch outputs
    with torch.no_grad():
        normalized = (test_obs - obs_mean) / obs_std
        h = torch.tanh(model.actor.fc1(normalized))
        h = torch.tanh(model.actor.fc2(h))
        pytorch_actions = torch.tanh(model.actor.fc3(h))
    
    pytorch_actions = pytorch_actions.cpu().numpy()
    test_obs_np = test_obs.cpu().numpy()
    
    # Create C test program
    test_code = f'''
#include <stdio.h>
#include "{os.path.abspath(header_path)}"

int main() {{
    float obs[{obs_mean.shape[0]}];
    float action[4];
    
    // Read test cases from stdin
    while (scanf("%f", &obs[0]) == 1) {{
        for (int i = 1; i < {obs_mean.shape[0]}; i++) {{
            scanf("%f", &obs[i]);
        }}
        
        rl_tools::rl::environments::l2f::forward(obs, action);
        
        for (int i = 0; i < 4; i++) {{
            printf("%.8f ", action[i]);
        }}
        printf("\\n");
    }}
    
    return 0;
}}
'''
    
    with tempfile.TemporaryDirectory() as tmpdir:
        # Write test program
        test_path = os.path.join(tmpdir, "test.cpp")
        with open(test_path, 'w') as f:
            f.write(test_code)
        
        # Compile
        exe_path = os.path.join(tmpdir, "test")
        result = subprocess.run(
            ["g++", "-O2", "-o", exe_path, test_path],
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            print(f"Compilation failed: {result.stderr}")
            return False
        
        # Run with test inputs
        input_str = "\n".join(
            " ".join(f"{x:.8f}" for x in row)
            for row in test_obs_np
        )
        
        result = subprocess.run(
            [exe_path],
            input=input_str,
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            print(f"Execution failed: {result.stderr}")
            return False
        
        # Parse outputs
        c_actions = []
        for line in result.stdout.strip().split("\n"):
            if line:
                c_actions.append([float(x) for x in line.split()])
        
        c_actions = np.array(c_actions)
        
        # Compare
        max_diff = np.max(np.abs(pytorch_actions - c_actions))
        mean_diff = np.mean(np.abs(pytorch_actions - c_actions))
        
        print(f"Validation: max_diff={max_diff:.2e}, mean_diff={mean_diff:.2e}")
        
        if max_diff > tolerance:
            print(f"FAILED: max_diff {max_diff} > tolerance {tolerance}")
            return False
        
        print("PASSED: C header matches PyTorch output")
        return True
